### ISSUE TITLE
PDC not fully shown

### ISSUE THREAD

**Issue by laurenzooz** [josh-seagrave/EasyCPDLC#9] opened 2021-11-03 12:29 UTC
Hi, had this issue in ENGM on vatsim, the PDC was not fully visible in the client.

From the log:

> 2021-11-01 20:29:08.5592|DEBUG|EasyCPDLC.MainForm|RECEIVED: ok {ENGM cpdlc {/data2/10//WU/ENGM PDC 004 . . . . . CLD 1829 211101 ENGM PDC 004 @NSZ3240@ ENGM PDC004 CLD 1829 211101 @NSZ3240@ CLRD TO @EKCH@ OFF @19L@ VIA @OKSAT2C@ SQUAWK @4677@ REPORT READY ON @118.300@ @QNH 994@ END OF MESSAGE}} 
> 
> 2021-11-01 20:29:08.5592|DEBUG|EasyCPDLC.MainForm|CPDLC Message identified, attempting to parse
> 
> 2021-11-01 20:29:08.5592|DEBUG|EasyCPDLC.MainForm|Writing message: NSZ3240 ENGM PDC004 CLD 1829 211101

So the client didn't print the full clearance. Had no issues in EGPH, haven't tried in other airports yet but will report the results (maybe the format is slightly different depending on atc division? Don't know)

Keep up the good work! Loving it so far

**Comment by josh-seagrave** [comment] 2021-11-03 13:56
Hi, thanks for the report!

I think I know why this is, I'm just in the final stages of compiling a new build but I'll get a fix for this included!

**Comment by josh-seagrave** [comment] 2021-11-03 14:03
Your hunch about the format being the cause is correct 😅 I've been trying desperately to not print all of the header stuff but each FIR seems to have a slightly different format, so sometimes my parsing function doesn't quite get it right.

**Closed** 2021-11-06 22:11 UTC
Labels: bug
