### ISSUE TITLE
Handover not changing the active station

### ISSUE THREAD

**Issue by JANXOL** [josh-seagrave/EasyCPDLC#21] opened 2021-12-10 22:09 UTC
I was using cpdlc during a flight, managed to logon to edgg, then when i was handed off to edgd things stopped working. 
I received handoff message and a "logon accepted" message from the new station, but the client still showed me connected to edgg and edgd controller was unable to reach me via cpdlc. Log file attached.

[EasyCPDLCLog.txt](https://github.com/josh-seagrave/EasyCPDLC/files/7695702/EasyCPDLCLog.txt)

Also, i attempted to respon with WILCO to the handoff message thinking i need to acknowledge the handoff - this produced unhandled exception as referenced here: [Issue](https://github.com/josh-seagrave/EasyCPDLC/issues/20)

**Comment by josh-seagrave** [comment] 2021-12-10 22:13
Hi!

Thanks for the report, I think I managed to break handovers in the last update! 😨 

Luckily, I've just about finished developing everything else for the next build so I'll see if the fix for this can be included in the next update, which is due tomorrow.

**Comment by josh-seagrave** [comment] 2021-12-10 22:32
Ah! Got it. I think I know the root cause of both issues here.

1) The client showed you connected to the wrong station because I refactored the way storing which ATC unit was current was done, and forgot to change it over for a HANDOVER. That's just an oversite on my part and will be fixed.

2) The crash on WILCO for the handoff message was because you had actually been transferred to EGDG, despite what the client was telling you, and therefore it couldn't send a CPDLC message to EDGG, raising an exception. I've included some error handling here and a check to ensure that the current ATC unit and intended recipient are the same before allowing you to reply to a message. This should prevent that issue occurring in future.

As to the "WILCO" option even being available for the handoff message, that's a limitation of the message formatting that TopSky sends, where even if the controller transfers the CPDLC connection, the contact message still expects a response. This is outside of my control at the moment, all I can do is just make sure that if it does occur, it doesn't raise an exception and is handled appropriately. I can only apologise for this.

Both fixes will be included in the next build of EasyCPDLC.

**Comment by JANXOL** [comment] 2021-12-10 22:59
Bear in mind the controller on edgd was unable to reach me via cpdlc after the handoff so it might be more than display error.

**Comment by josh-seagrave** [comment] 2021-12-10 23:19
> Bear in mind the controller on edgd was unable to reach me via cpdlc after the handoff so it might be more than display error.

https://www.hoppie.nl/acars/system/callsign.html?network=VATSIM&callsign=EDGD

According to the Hoppie logs, he didn't try.

**Closed** 2021-12-15 08:47 UTC
Labels: bug
