### ISSUE TITLE
CPDLC messages are not synchronised 

### ISSUE THREAD

**Issue by jakobeng1303** [josh-seagrave/EasyCPDLC#4] opened 2021-10-25 21:15 UTC
Despite starting the client as admin, the messages sometimes won't synchronise on the client. I would receive several messages after reconnecting, while I should have received them earlier according to the hoppie log. It just happens after a while. No idea why

**Comment by jakobeng1303** [comment] 2021-10-30 15:38
I again only received a TELEX once I reconnected
[EasyCPDLCLog.txt](https://github.com/josh-seagrave/EasyCPDLC/files/7447007/EasyCPDLCLog.txt)

**Comment by josh-seagrave** [comment] 2021-10-31 11:39
Thankyou very very much for the log file. It's been massively helpful. I now have a working hypothesis for what exactly is causing your issue.

The logfile reveals that about 7 minutes after starting the application, EasyCPDLC failed to poll for received messages once, and that then stopped the routine that runs that check every approx. 10-12 seconds. I've done some digging as to why that is the case and discovered that in the case of a request not being sent, the routine cancels without handling the error but the program continues to run as the error is self contained. More importantly, it does not notify the user of the error or attempt to restart the routine. I suspect that this is the root cause of your problems. As you correctly identified, logging out and back in restarts the routine so your message then came through.

I will develop a thorough fix for this and include it in the next development build of EasyCPDLC, which will be available hopefully by the end of today. As far as I can deduce that will fix this issue.

Thankyou again for your patience and your cooperation with helping me get this fixed, it is much appreciated

**Comment by jakobeng1303** [comment] 2021-10-31 11:43
> Thank you again for your patience and your cooperation with helping me get this fixed, it is much appreciated

No worries at all, happy to help and thanks for developing it! A user friendly CPDLC client is desperately needed and would hopefully encourage more people to use it, hence improving coverage and pressuring developers to incude it natively

**Closed** 2021-11-06 22:11 UTC
Labels: bug
